---
## 3. OPERACJE NA DANYCH – FILTROWANIE I TRANSFORMACJA

In [ ]:
## ZADANIE ##
#Sprawdź i wyświetl 3 rzeczy:
# 1. jaki jest typ zmiennej produkt, 
# 2. jakiego typu jest obiekt pod kluczem funkcje
# 3. jakiego typu jest drugi obiekt pod kluczem funkcje

produkt = {
    'kategoria':        'AGD',
    'produkt':       'pralka',
    'cena': 5600,
    'funkcje':    ['pranie', 'szybki_15min', 'wirowanie']
}

In [ ]:

type(produkt)

dict

In [ ]:

type(produkt['funkcje'])

list

In [ ]:

type(produkt['funkcje'][1])

str

In [1]:
import pandas as pd

In [2]:
# Dane produktów w sklepie
produkty = pd.DataFrame({
    'nazwa':      ['Laptop', 'Monitor', 'Klawiatura', 'Mysz'],
    'cena':       [3499, 1299, 249, 129],
    'stan_mag':   [12, 8, 45, 60],
    'kategoria':  ['Komputery', 'Komputery', 'Akcesoria', 'Akcesoria']
})

In [ ]:
# Filtrowanie – produkty droższe niż 500 zł
produkty[produkty['cena'] > 500]

     nazwa  cena  stan_mag  kategoria
0   Laptop  3499        12  Komputery
1  Monitor  1299         8  Komputery

Cofnijmy się jednak o krok. Co się dzieje w warunku porównania? Dostajemy Serię danych kolumny cena z wartościami True False. to tak jakby powiedzieć:
produkty[z kolumny cena weź te wieersze, gdzie warunek jest spełniony (True)]

In [4]:
produkty['cena'] > 500

0     True
1     True
2    False
3    False
Name: cena, dtype: bool

In [8]:
# Filtrowanie z wieloma warunkami
produkty[(produkty['kategoria'] == 'Komputery') & (produkty['stan_mag'] > 8)]

    nazwa  cena  stan_mag  kategoria
0  Laptop  3499        12  Komputery

wiemy, że True & True daje True i w tym filtrowaniu dzieje się dokładnie to samo! rodukty[ True & True = True (z dwóch warunków dadzą True i tylko te wiersze będą uwzglednione)]

In [10]:
# Dodanie nowej kolumny – wartość magazynowa
produkty['wartosc_mag'] = produkty['cena'] * produkty['stan_mag']
produkty

        nazwa  cena  stan_mag  kategoria  wartosc_mag
0      Laptop  3499        12  Komputery        41988
1     Monitor  1299         8  Komputery        10392
2  Klawiatura   249        45  Akcesoria        11205
3        Mysz   129        60  Akcesoria         7740

na skutek dodania kolumny jest ona już uwzględniona w dataframe!

In [ ]:
# Kolumna z kategorią cenową
def kategoria_cenowa(cena):
    if cena >= 1000:
        return 'premium'
    elif cena >= 300:
        return 'srednia'
    else:
        return 'budzetowa'

produkty['segment'] = produkty['cena'].apply(kategoria_cenowa)
print(produkty)

In [12]:
# Sortowanie po wartości magazynowej
#https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html
produkty.sort_values('wartosc_mag', ascending=False)

        nazwa  cena  stan_mag  kategoria  wartosc_mag
0      Laptop  3499        12  Komputery        41988
2  Klawiatura   249        45  Akcesoria        11205
1     Monitor  1299         8  Komputery        10392
3        Mysz   129        60  Akcesoria         7740

In [11]:
produkty.sort_values('wartosc_mag')

        nazwa  cena  stan_mag  kategoria  wartosc_mag
3        Mysz   129        60  Akcesoria         7740
1     Monitor  1299         8  Komputery        10392
2  Klawiatura   249        45  Akcesoria        11205
0      Laptop  3499        12  Komputery        41988

In [13]:
# Podstawowe statystyki
print("Średnia cena:   ", produkty['cena'].mean())
print("Odch. std. ceny:", produkty['cena'].std())
print()
print(produkty.describe())

Średnia cena:    1294.0
Odch. std. ceny: 1561.121391820636

              cena   stan_mag   wartosc_mag
count     4.000000   4.000000      4.000000
mean   1294.000000  31.250000  17831.250000
std    1561.121392  25.342652  16172.317158
min     129.000000   8.000000   7740.000000
25%     219.000000  11.000000   9729.000000
50%     774.000000  28.500000  10798.500000
75%    1849.000000  48.750000  18900.750000
max    3499.000000  60.000000  41988.000000

---
## 4. FUNKCJE

In [ ]:
#str z parametrem/zmienną/formatowaniem zmiennej
# https://www.w3schools.com/python/python_string_formatting.asp
price = 59
txt = f"The price is {price} dollars"
print(txt)

In [ ]:
# Definicja prostej funkcji
def oblicz_vat(cena_netto, stawka=0.23):
    vat = cena_netto * stawka
    brutto = cena_netto + vat
    print(f"Cena netto: {cena_netto} zł | VAT: {vat:.2f} zł | Brutto: {brutto:.2f} zł")
    return brutto

oblicz_vat(500)
oblicz_vat(500, stawka=0.08)  # stawka obniżona

In [ ]:
### ZADANIE ###
# Stwórz funkcję, która przyjmie listę cen produktów i zwróci ich średnią

In [ ]:


def srednia_cen(ceny):
    return sum(ceny) / len(ceny)

ceny_produktow = [199, 349, 89, 499, 129]
print(srednia_cen(ceny_produktow))

In [ ]:
# Funkcja z wartością domyślną
def powitanie_klienta(imie='Kliencie', godzina=12):
    if godzina < 12:
        pora = 'Dzień dobry'
    elif godzina < 18:
        pora = 'Dzień dobry'
    else:
        pora = 'Dobry wieczór'
    return f"{pora}, {imie}!"

print(powitanie_klienta())
print(powitanie_klienta('Marta', godzina=19))

In [ ]:
# Funkcja z warunkami – ocena rentowności
def ocena_rentownosci(marza):
    if marza >= 0.30:
        return 'wysoka'
    elif marza >= 0.15:
        return 'średnia'
    else:
        return 'niska'

print(ocena_rentownosci(0.35))
print(ocena_rentownosci(0.20))
print(ocena_rentownosci(0.08))

In [ ]:
# Funkcja z dwoma zmiennymi
def zysk(przychod, koszt):
    return przychod - koszt

zysk(150000, 98000)

---
## 5. PĘTLE

In [ ]:
# Pętla for – iteracja po zakresie
for miesiac in range(1, 7):
    print(f"Miesiąc: {miesiac}")

In [ ]:
# Iteracja po liście elementów
dzialy = ['Sprzedaż', 'Marketing', 'Finanse', 'IT']
for dzial in dzialy:
    print(f"Dział: {dzial}")

In [ ]:
# Pętla while – symulacja spłaty pożyczki
saldo = 10000
rata = 2500
miesiac = 1

while saldo > 0:
    saldo -= rata
    if saldo < 0:
        saldo = 0
    print(f"Miesiąc {miesiac}: pozostałe saldo = {saldo} zł")
    miesiac += 1

In [ ]:
# break i continue
#https://www.w3schools.com/python/ref_func_range.asp
for i in range(1, 10):
    if i == 4:
        continue   # pomija i=4
    if i == 7:
        break      # kończy pętlę przy i=7
    print(f"i = {i}")

In [ ]:
### ZADANIE 2 ###
# Napisz pętlę for, która wypisze wszystkie miesiące (1–12),
# ale tylko te, które są kwartałami (tj. 3, 6, 9, 12)

In [ ]:

for m in range(1, 13):
    if m % 3 == 0:
        print(f"Koniec kwartału: miesiąc {m}")

In [ ]:
### ZADANIE 3 ###
# Masz listę transakcji. Oblicz sumę tylko tych,
# których wartość przekracza 1000 zł.

In [ ]:


transakcje = [450, 1200, 890, 2300, 750, 1800, 300]
suma_duzych = 0

for t in transakcje:
    if t > 1000:
        suma_duzych += t

print(f"Suma dużych transakcji: {suma_duzych} zł")

# Elegantszy sposób – składnia list comprehension:
suma_duzych2 = sum(t for t in transakcje if t > 1000)
print(f"Wynik (list comprehension): {suma_duzych2} zł")